#!/bin/bash
#
#

context="$1"
if [ "$context" == "" ]; then
	echo "$0 [context]"
	exit 1
fi

dev_id=1jfiegbrmeg3q
pass_mp=d4BwZ8nVU2mgfHDeOJhyjQ
pass_up=MEJLfM11UhRkaCvcFt1GyQ
echo -n "${dev_id}${context}${pass_mp}${pass_up}" | md5sum | awk '{print $1}'
